<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="UpdateEventTimeStampWithSystemTime" Id="{b9f8f8a5-76bd-4064-870e-869130b00d90}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateEventTimeStampWithSystemTime 
VAR_INPUT
	ST_Event:  REFERENCE TO ST_Event;
END_VAR
VAR
	FbGETSYSTEMTIME : GETSYSTEMTIME; // Bu FONKSİYON BİZE sistem zamanını veriyor.

	st_FILETIME : T_FILETIME; // Bu structa saklıyoruz sistemden çektiğimiz saati. Çünkü biz DATE TIME döüştürmemiz grekiyor bunun için de önce FILETIME kaydettik buradan dönüştürecez.

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FbGETSYSTEMTIME(timeLoDW => st_FILETIME.dwLowDateTime,
	            timeHiDW => st_FILETIME.dwHighDateTime);
				
	ST_Event.dtTimestamp:= FILETIME_TO_DT(fileTime := st_FILETIME);
	
				
				
	             ]]></ST>
    </Implementation>
    <LineIds Name="UpdateEventTimeStampWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="21" Count="2" />
      <LineId Id="20" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="14" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>