<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="POU" Id="{06e6837e-abdc-4596-b423-197af08c097a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	a , b, c : INT := 5;
	d : INT ;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[d := a+b+c+d;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>